@startuml JobHistory
title Job History
    class Job{
        _company:string
        _jobTitle:string
        _startYear:int
        _endYear:int
        Display():void
    }
    class Resume{
        _name:string
        _jobs:List<Job>
        Display():void
    }
@enduml